server:
  port: 8080

spring:
  flyway:
    create-schemas: true
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Rjdfk`df666222
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://ipfran.ru/
      name: pfran.ru
    - url: https://www.svetlovka.ru/
      name: svetlovka.ru
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com
search:
  engine:
    db:
      url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: Rjdfk`df666222

      ENV: DB_PASSWORD=Rjdfk`df666222;
        DB_URL=jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true;
        DB_USER_NAME=root
